/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABPeoplePickerNavigationControllerDelegate.h"
#import "MobilePhone-Structs.h"


@protocol ABPeoplePickerNavigationControllerPrivateMemberCellDelegate <ABPeoplePickerNavigationControllerDelegate>
@optional
-(BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void*)person property:(int)property identifier:(int)identifier withMemberCell:(id)memberCell;
-(BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void*)person withLinkedPeople:(CFArrayRef)linkedPeople memberCell:(id)cell;
@end

