/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class AVController, NSDictionary, NSArray;

__attribute__((visibility("hidden")))
@interface AudioDeviceController : XXUnknownSuperclass {
	id _delegate;
	AVController* _avController;
	NSDictionary* _pickedRoute;
	NSArray* _pickableRoutes;
}
-(void)callAudioRouteChangedEventHandler:(id)handler;
-(void)_registerForAVControllerNotifications;
-(void)_pickableRoutesChanged;
-(void)_mediaServerDied;
-(BOOL)_routeIsHandset:(id)handset;
-(BOOL)_routeIsDefault:(id)aDefault;
-(BOOL)_routeIsReceiver:(id)receiver;
-(BOOL)_routeIsSpeaker:(id)speaker;
-(BOOL)_routeIsAirTunes:(id)tunes;
-(BOOL)_routeIsAirPlayMirroring:(id)mirroring;
-(BOOL)_routeIsBlueToothLEA:(id)lea;
-(BOOL)isAirPlayMirroring;
-(void)_pickRoute:(id)route;
-(id)_pickableRoutes;
-(id)_pickedRoute;
-(void)pickRouteAtIndex:(unsigned)index;
-(id)routeNameAtIndex:(unsigned)index isPicked:(BOOL*)picked;
-(BOOL)audioCategoryIsTTY;
-(BOOL)receiverRouteIsPicked;
-(BOOL)speakerRouteIsPicked;
-(void)clearCachedRoutes;
-(void)restorePickedRoute;
-(BOOL)pickRouteWithUID:(id)uid;
-(BOOL)pickDefaultRoute;
-(BOOL)pickHandsetRoute;
-(BOOL)pickSpeakerRoute;
-(BOOL)handsetRouteAvailable;
-(BOOL)speakerRouteAvailable;
-(int)numberOfAudioRoutes;
-(BOOL)auxiliaryAudioRoutesAvailable;
-(void)setDelegate:(id)delegate;
-(void)invalidateAVController;
-(void)setAVController:(id)controller;
-(void)dealloc;
-(id)init;
@end

