/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ConferenceManagementTable : XXUnknownSuperclass {
}
-(void)completeRowDeletionAnimation;
-(void)animateDeletionOfRowWithCell:(id)cell viaEdge:(unsigned)edge;
-(id)initWithFrame:(CGRect)frame;
@end

