/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol DialerViewDelegate <NSObject>
@optional
-(void)dialerViewPhoneNumberWasTapped:(id)tapped;
-(void)dialerView:(id)view stringWasPasted:(id)pasted;
-(void)dialerViewTextDidChange:(id)dialerViewText;
@end

