/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol DialerLCDFieldProtocol <NSObject>
-(void)setDelegate:(id)delegate;
-(void)setHighlighted:(BOOL)highlighted;
-(BOOL)highlighted;
-(void)setInCallMode:(BOOL)callMode;
-(BOOL)inCallMode;
-(void)deleteCharacter;
-(void)setText:(id)text needsFormat:(BOOL)format;
-(id)text;
@optional
-(void)setText:(id)text needsFormat:(BOOL)format name:(id)name label:(id)label;
-(void)setName:(id)name numberLabel:(id)label;
@end

