/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol IDSIDQueryControllerDelegate <NSObject>
@optional
-(void)idStatusUpdatedForDestinations:(id)destinations service:(id)service;
@end

