/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIButton;

__attribute__((visibility("hidden")))
@interface InCallLCDField : XXUnknownSuperclass {
	UIButton* _button;
	id _delegate;
	unsigned _textIsPlaceholder : 1;
	unsigned _buttonIsDelete : 1;
}
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(CGRect)textFrame;
-(id)unformattedText;
-(id)text;
-(void)setText:(id)text;
-(void)setPlaceholderText:(id)text animating:(BOOL)animating;
-(void)setShowsDeleteButton:(BOOL)button;
-(void)_deleteButtonClicked:(id)clicked;
-(void)_sendButtonClicked:(id)clicked;
-(BOOL)showsSendButton;
-(void)setShowsSendButton:(BOOL)button;
-(void)_showButtonWithTitle:(id)title action:(SEL)action;
-(void)_removeButton;
-(void)_updateButton;
-(void)setDelegate:(id)delegate;
-(void)dealloc;
@end

