/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import "PhoneApplication.h"

@class TUCall;

__attribute__((visibility("hidden")))
@interface MobilePhoneApplication : PhoneApplication {
	BOOL _outstandingDecline;
	TUCall* _outstandingDeclineCall;
}
@property(retain) TUCall* outstandingDeclineCall;
@property(assign) BOOL outstandingDecline;
-(BOOL)showsPhoneVoicemail;
-(BOOL)dialerIsNumericOnly;
-(BOOL)showsPhoneDialer;
-(BOOL)badgesMissedFaceTime;
-(BOOL)badgesMissedFaceTimeAudio;
-(BOOL)badgesMissedTelephonyCalls;
-(BOOL)showsFaceTimeRecents;
-(BOOL)showsFaceTimeAudioRecents;
-(BOOL)showsTelephonyRecents;
-(BOOL)showsFaceTimeFavorites;
-(BOOL)showsFaceTimeAudioFavorites;
-(BOOL)showsTelephonyFavorites;
-(BOOL)showsFaceTimeAudio;
-(BOOL)showsFaceTime;
-(BOOL)showsTelephonyCalls;
-(int)defaultAction;
-(BOOL)showSplashScreenOnSignin;
-(BOOL)tabBarCanSlide;
-(BOOL)tabBarFillsScreen;
-(BOOL)contentViewCanRotate;
-(BOOL)alwaysShowVideoConferenceController;
-(BOOL)usesBlendModes;
-(int)addressBookUIStyle;
-(int)wizardGlobalAppearanceStyle;
-(unsigned)userInterfaceStyle;
-(void)_incomingCallEnded;
-(void)_stopCaringAboutDecline;
-(void)_handlePhoneAppHeardAboutDecline;
-(void)handleResumeEvent:(GSEventRef)event;
-(void)dealloc;
-(void)applicationDidFinishLaunching:(id)application;
-(BOOL)_isIPad;
-(id)_keyWindowForScreen:(id)screen;
@end

