/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DialerLCDFieldDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIControl, UIView;
@protocol DialerLCDFieldProtocol, TPDialerKeypadProtocol, DialerViewDelegate;

__attribute__((visibility("hidden")))
@interface PHAbstractDialerView : XXUnknownSuperclass <DialerLCDFieldDelegate> {
	BOOL _inCallMode;
	UIView<DialerLCDFieldProtocol>* _lcdView;
	UIView<TPDialerKeypadProtocol>* _phonePadView;
	id<DialerViewDelegate> _delegate;
	UIControl* _addContactButton;
	UIControl* _callButton;
	UIControl* _deleteButton;
}
@property(retain, nonatomic) UIControl* deleteButton;
@property(retain, nonatomic) UIControl* callButton;
@property(retain, nonatomic) UIControl* addContactButton;
@property(assign, nonatomic) id<DialerViewDelegate> delegate;
@property(retain, nonatomic) UIView<TPDialerKeypadProtocol>* phonePadView;
@property(retain, nonatomic) UIView<DialerLCDFieldProtocol>* lcdView;
@property(assign, nonatomic) BOOL inCallMode;
-(void)dialerField:(id)field stringWasPasted:(id)pasted;
-(void)dialerLCDFieldTextDidChange:(id)dialerLCDFieldText;
-(void)dealloc;
@end

