/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABPeoplePickerNavigationControllerDelegate.h"
#import "MobilePhone-Structs.h"
#import "PhoneTabViewController.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface PHAddressBookController : XXUnknownSuperclass <PhoneTabViewController, ABPeoplePickerNavigationControllerDelegate> {
	int _abuiStyle;
}
@property(assign) void* savedPerson;
@property(readonly, assign) BOOL shouldSaveAndRestoreState;
@property(assign) int abuiStyle;
+(id)defaultPNGName;
+(id)tabBarIconName;
+(XXStruct_ndkk2A)badge;
+(int)tabBarSystemItem;
+(int)tabViewType;
-(void)_applicationDeactivated;
-(void)_restoreState;
-(void)_saveState;
-(BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void*)person property:(int)property identifier:(int)identifier;
-(BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void*)person;
-(void)peoplePickerNavigationControllerDidCancel:(id)peoplePickerNavigationController;
-(void)handleURL:(id)url;
-(void)prepareForSnapshot;
-(BOOL)shouldSnapshot;
-(BOOL)tabBarControllerShouldSelectViewController:(id)tabBarController;
-(void)presentViewController:(id)controller animated:(BOOL)animated completion:(id)completion;
-(void)pushViewController:(id)controller animated:(BOOL)animated;
-(void)applicationWillSuspend;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)loadView;
-(void)_updatePickerBanner:(id)banner;
-(void)_updatePickerPhoneNumber:(id)number;
-(void)dealloc;
-(id)initWithStyle:(int)style;
@end

