/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AVCaptureFileOutputRecordingDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class AVCaptureConnection, NSTimer, NSError, NSString, AVCaptureSession, AVCaptureMovieFileOutput;
@protocol PHAudioRecorderDelegate;

__attribute__((visibility("hidden")))
@interface PHAudioRecorder : XXUnknownSuperclass <AVCaptureFileOutputRecordingDelegate> {
	AVCaptureSession* _captureSession;
	AVCaptureMovieFileOutput* _captureFileOutput;
	AVCaptureConnection* _captureConnection;
	NSError* _buildCaptureSessionError;
	NSTimer* _updateTimer;
	BOOL _isRecording;
	BOOL _handlingStop;
	NSString* _outputFile;
	id<PHAudioRecorderDelegate> _audioRecorderDelegate;
	double _maxRecordedDuration;
}
@property(retain, nonatomic) NSTimer* updateTimer;
@property(assign) BOOL handlingStop;
@property(readonly, assign) NSError* buildCaptureSessionError;
@property(readonly, assign) AVCaptureConnection* captureConnection;
@property(readonly, assign) AVCaptureMovieFileOutput* captureFileOutput;
@property(readonly, assign) AVCaptureSession* captureSession;
@property(assign) BOOL isRecording;
@property(assign) id<PHAudioRecorderDelegate> audioRecorderDelegate;
@property(assign, nonatomic) double maxRecordedDuration;
@property(retain, nonatomic) NSString* outputFile;
-(void)_stopWithError:(id)error;
-(void)_buildCaptureSessionAndOutputIfNecessary;
-(void)_updateRecordProgress:(id)progress;
-(void)_captureSessionErrored:(id)errored;
-(void)_captureSessionWasInterrupted:(id)interrupted;
-(void)captureOutput:(id)output didFinishRecordingToOutputFileAtURL:(id)url fromConnections:(id)connections error:(id)error;
-(void)stop;
-(BOOL)startWithError:(id*)error;
-(void)dealloc;
-(id)init;
@end

