/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol PHAudioRecorderDelegate
-(void)audioRecorderEndedWithFile:(id)file duration:(double)duration error:(id)error;
-(void)audioRecorderContinuedWithFile:(id)file duration:(double)duration;
-(void)audioRecorderStartedWithFile:(id)file;
@end

