/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol PHAudioPlayerDelegate
-(void)stoppedPlayingWithDataSource:(id)dataSource withError:(id)error;
-(void)updateWithElapsedTime:(double)elapsedTime playableTime:(double)time totalTime:(double)time3 isPlaying:(BOOL)playing isPlayable:(BOOL)playable dataSource:(id)source;
-(void)startedPlayingWithDataSource:(id)dataSource;
@end

