/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSTimer, PHVoicemailAudioController, NSNumber, NSObject;
@protocol PHAudioPlayerDelegate, PHAudioPlayerDataSource;

__attribute__((visibility("hidden")))
@interface PHAudioPlayer : XXUnknownSuperclass {
	PHVoicemailAudioController* _audioController;
	NSNumber* _seekToTime;
	BOOL _isPlaying;
	BOOL _isPlayable;
	BOOL _progressiveDurationAvailable;
	NSObject<PHAudioPlayerDataSource>* _dataSource;
	float _elapsedTime;
	float _playableTime;
	float _totalTime;
	id<PHAudioPlayerDelegate> _audioPlayerDelegate;
	float _progressBarWidth;
	NSTimer* _delayedPlaybackTimer;
	NSTimer* _progressUpdateTimer;
	unsigned _currentFileSize;
	unsigned _expectedFileSize;
}
@property(assign) BOOL progressiveDurationAvailable;
@property(assign) unsigned expectedFileSize;
@property(assign) unsigned currentFileSize;
@property(assign, nonatomic) NSTimer* progressUpdateTimer;
@property(assign, nonatomic) NSTimer* delayedPlaybackTimer;
@property(assign, nonatomic) float progressBarWidth;
@property(assign, nonatomic) id<PHAudioPlayerDelegate> audioPlayerDelegate;
@property(readonly, assign) PHVoicemailAudioController* audioController;
@property(assign) float totalTime;
@property(assign) float playableTime;
@property(assign) float elapsedTime;
@property(retain, nonatomic) NSObject<PHAudioPlayerDataSource>* dataSource;
@property(assign) BOOL isPlayable;
@property(assign) BOOL isPlaying;
+(id)sharedAudioPlayer;
-(void)_proximityStateChanged:(id)changed;
-(void)_handlePlayableDurationChanged:(id)changed;
-(void)_updateDurations;
-(void)_forceUpdateProgressiveDataLengths;
-(BOOL)_fileExists:(id)exists;
-(void)seekToTime:(float)time;
-(void)_stopPlayingWithError:(id)error;
-(void)stop;
-(void)_updateProgress;
-(BOOL)_updateElapsedTime;
-(void)_setupProgressUpdateTimer;
-(void)_avControllerDied:(id)died;
-(void)_avControllerPlaybackInterrupted:(id)interrupted;
-(void)_avControllerPlaybackRateChanged:(id)changed;
-(void)_avControllerPlaybackDidEnd:(id)_avControllerPlayback;
-(void)_avControllerPlaybackStateDidChangeItem:(id)_avControllerPlaybackState;
-(void)_avControllerTimeJumped:(id)jumped;
-(void)_start;
-(BOOL)_createVoicemailAVItemIfNecessary:(id*)necessary;
-(void)start;
-(void)dealloc;
-(id)init;
@end

