/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIButton, UILabel;
@protocol PHConferenceParticipantCellProtocol;

__attribute__((visibility("hidden")))
@interface PHConferenceParticipantCell : XXUnknownSuperclass {
	BOOL _shouldShowPrivateButton;
	id<PHConferenceParticipantCellProtocol> _delegate;
	UILabel* _nameLabel;
	UIButton* _endCallButton;
	UIButton* _privateButton;
}
@property(assign) UIButton* privateButton;
@property(assign) UIButton* endCallButton;
@property(assign, nonatomic) BOOL shouldShowPrivateButton;
@property(readonly, assign) UILabel* nameLabel;
@property(assign) id<PHConferenceParticipantCellProtocol> delegate;
-(void)makeHeld;
-(void)buttonTapped:(id)tapped;
-(void)setRepresentedCall:(id)call;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

