/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import "PHHandsetDialerView.h"


__attribute__((visibility("hidden")))
@interface PHEmergencyHandsetDialerView : PHHandsetDialerView {
}
-(id)layoutConstraintMetrics;
-(id)newCallButton;
-(id)newNumberPadView;
-(id)newLCDView;
-(void)createConstraints;
-(id)dialerColor;
-(id)initWithFrame:(CGRect)frame;
@end

