/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import "PHHandsetDialerLCDView.h"

@class PHTextCycleLabel;

__attribute__((visibility("hidden")))
@interface PHEmergencyHandsetDialerLCDView : PHHandsetDialerLCDView {
	PHTextCycleLabel* _emergencyTitleLabel;
}
@property(readonly, assign) PHTextCycleLabel* emergencyTitleLabel;
-(void)applyLayoutConstraints;
-(id)newDeleteButton;
-(id)newNameAndLabelView;
-(id)numberLabelFont;
-(id)lcdColor;
-(float)frameHeight;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame forDialerType:(int)dialerType;
@end

