/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage;

__attribute__((visibility("hidden")))
@interface PHFavoritesEntry : XXUnknownSuperclass {
	UIImage* _thumbnail;
	BOOL _isPersonImage;
}
@property(assign, nonatomic) BOOL isPersonImage;
+(id)sharedMonogrammer;
+(BOOL)_usesFlatImages;
-(void)dealloc;
-(id)thumbnail;
-(void)loadThumbnailIfNecessary;
@end

