/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class PHFavoritesEntry, UIImageView;

__attribute__((visibility("hidden")))
@interface PHFavoritesContactPhotoView : XXUnknownSuperclass {
	PHFavoritesEntry* _entry;
	UIImageView* _imageView;
}
@property(retain, nonatomic) UIImageView* imageView;
@property(assign, nonatomic) PHFavoritesEntry* entry;
+(float)defaultDiameter;
-(void)handleAddressBookChangedNotification:(id)notification;
-(CGSize)intrinsicContentSize;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

