/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class PHFavoritesEntry, UILabel, UIImageView, PHFavoritesContactPhotoView, NSLayoutConstraint, NSArray;

__attribute__((visibility("hidden")))
@interface PHFavoritesCell : XXUnknownSuperclass {
	UILabel* _titleTextLabel;
	UILabel* _labelTextLabel;
	UIImageView* _iconGlyphView;
	PHFavoritesContactPhotoView* _contactPhotoView;
	long _buildConstraintsOnceToken;
	NSLayoutConstraint* _contactPhotoLeftInsetConstraint;
	NSArray* _mutableConstraints;
	NSLayoutConstraint* _rightViewRightInsetConstraint;
	NSLayoutConstraint* _titleLeftInsetConstraint;
	PHFavoritesEntry* _favoritesEntry;
}
@property(readonly, assign) BOOL shouldShowContactPhotos;
@property(readonly, assign) BOOL shouldShowIconGlyph;
@property(readonly, assign) BOOL shouldShowTextLabel;
@property(assign, nonatomic) PHFavoritesEntry* favoritesEntry;
+(float)height;
+(id)faceTimeAudioGlyphPress;
+(id)faceTimeAudioGlyph;
+(id)faceTimeGlyphPress;
+(id)faceTimeGlyph;
+(float)editingMarginWidth;
+(float)marginWidth;
+(BOOL)shouldShowContactPhotos;
-(void)_updateFonts;
-(BOOL)_drawsTopSeparatorDuringReordering;
-(void)_setReordering:(BOOL)reordering;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)_populateSubviewsFromFavoritesItem;
-(void)_rebuildMutableConstraints;
-(void)_handleContentSizeCategoryDidChange:(id)_handleContentSizeCategory;
-(void)_handleFavoritesShowsContactPhotosChanged:(id)changed;
-(void)_handleFavoritesEntryChanged:(id)changed;
-(void)layoutSubviews;
-(void)updateConstraints;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

