/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABUnknownPersonViewControllerDelegate.h"
#import "ABPeoplePickerNavigationControllerPrivateMemberCellDelegate.h"
#import "MobilePhone-Structs.h"
#import "PhoneViewController.h"
#import "UIActionSheetDelegate.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"

@class _UIContentUnavailableView, ABPeoplePickerNavigationController, ABFavoritesEntry, UITableView, NSDictionary, UIActionSheet;

__attribute__((visibility("hidden")))
@interface PHFavoritesViewController : PhoneViewController <UITableViewDataSource, UITableViewDelegate, ABUnknownPersonViewControllerDelegate, ABPeoplePickerNavigationControllerPrivateMemberCellDelegate, UIActionSheetDelegate> {
	UITableView* _table;
	_UIContentUnavailableView* _noContentView;
	ABPeoplePickerNavigationController* _peoplePickerController;
	ABFavoritesEntry* _selectedABFavoritesEntry;
	UIActionSheet* _disambiguationSheet;
	NSDictionary* _disambiguationSheetContext;
	unsigned _suspended : 1;
	unsigned _ignoreFavoritesDidChangeNotification : 1;
	unsigned _postponeTableReloadFromFavoritesChange : 1;
	unsigned _needsTableReloadFromFavoritesChange : 1;
}
@property(readonly, assign) _UIContentUnavailableView* noContentView;
@property(readonly, assign) UITableView* table;
+(id)tabBarIconName;
+(int)tabBarSystemItem;
+(int)tabViewType;
+(BOOL)requiresNavigationControllerContainer;
-(void)unknownPersonViewController:(id)controller didResolveToPerson:(void*)person;
-(void)tableView:(id)view didEndEditingRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willBeginEditingRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
-(void)accessoryButtonTapped:(id)tapped withEvent:(id)event;
-(void)tableView:(id)view moveRowAtIndexPath:(id)indexPath toIndexPath:(id)indexPath3;
-(id)tableView:(id)view targetIndexPathForMoveFromRowAtIndexPath:(id)indexPath toProposedIndexPath:(id)proposedIndexPath;
-(BOOL)tableView:(id)view canMoveRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(void)deleteButtonPressedForIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(int)selectedIndex;
-(int)absoluteIndexOfFilteredIndex:(int)filteredIndex;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)_addButtonClicked:(id)clicked;
-(BOOL)peoplePickerNavigationController:(id)controller shouldAllowSelectingPersonWithRecordID:(int)recordID;
-(BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void*)person property:(int)property identifier:(int)identifier;
-(BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void*)person property:(int)property identifier:(int)identifier withMemberCell:(id)memberCell;
-(BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void*)person;
-(BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void*)person withLinkedPeople:(CFArrayRef)linkedPeople memberCell:(id)cell;
-(void)peoplePickerNavigationController:(id)controller insertEditorDidConfirm:(BOOL)insertEditor forPerson:(void*)person;
-(BOOL)peoplePickerNavigationController:(id)controller shouldShowInsertEditorForPerson:(void*)person insertProperty:(int*)property copyInsertValue:(id*)value copyInsertLabel:(id*)label;
-(void)peoplePickerNavigationControllerDidCancel:(id)peoplePickerNavigationController;
-(void)dismissPeoplePicker;
-(void)_addEntryFromPeoplePickerForPerson:(void*)person property:(int)property identifier:(int)identifier animateView:(id)view;
-(BOOL)usesPersonBasedFavorites;
-(id)buttonTitlesForPossibleFavoriteTypes:(id)possibleFavoriteTypes;
-(id)possibleFavoriteTypesForProperty:(int)property;
-(void)_addEntryFromPeoplePickerForPerson:(void*)person property:(int)property identifier:(int)identifier animateView:(id)view favoritesEntryType:(int)type;
-(void)showCardViewerForPerson:(void*)person withTitle:(id)title animate:(BOOL)animate;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)_updateNavButtons;
-(void)_favoritesManagerSignificantChangeNotification:(id)notification;
-(void)restoreState;
-(BOOL)shouldSnapshot;
-(void)unloadView;
-(void)didReceiveMemoryWarning;
-(void)savePreferences;
-(void)viewDidLoad;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)loadView;
-(void)_updateContentView;
-(BOOL)showsNoContentView;
-(void)_handleContentSizeCategoryDidChange:(id)_handleContentSizeCategory;
-(void)_handleFavoritesShowsContactPhotosChanged:(id)changed;
-(void)dealloc;
-(id)init;
@end

