/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import "PHAbstractDialerView.h"
#import "TPDialerKeypadDelegate.h"

@class UIView, NSLayoutConstraint;

__attribute__((visibility("hidden")))
@interface PHHandsetDialerView : PHAbstractDialerView <TPDialerKeypadDelegate> {
	UIView* _leftBlankView;
	UIView* _rightBlankView;
	UIView* _bottomBlankView;
	UIView* _topBlankView;
	NSLayoutConstraint* _statusBarToLCDViewConstraint;
	NSLayoutConstraint* _callButtonKeypadOffsetConstraint;
	UIView* _dimmingView;
}
@property(retain) UIView* dimmingView;
@property(retain) NSLayoutConstraint* callButtonKeypadOffsetConstraint;
@property(retain) NSLayoutConstraint* statusBarToLCDViewConstraint;
@property(retain) UIView* topBlankView;
@property(retain) UIView* bottomBlankView;
@property(retain) UIView* rightBlankView;
@property(retain) UIView* leftBlankView;
-(void)lcdViewTapped:(id)tapped;
-(id)layoutConstraintMetrics;
-(id)newCallButton;
-(id)newNumberPadView;
-(id)newLCDView;
-(id)dialerColor;
-(float)heightForCallButton;
-(void)updateContraintsForStatusBar;
-(void)setInCallMode:(BOOL)callMode;
-(void)createConstraints;
-(void)dealloc;
-(void)animateInFromDefaultPNG;
-(id)initWithFrame:(CGRect)frame;
@end

