/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

__attribute__((visibility("hidden")))
@interface PHHandsetDialerNameLabelView : XXUnknownSuperclass {
	BOOL _isShowingAddToContactsLabel;
	UILabel* _nameAndLabelLabel;
	UILabel* _addToContactsLabel;
}
@property(assign) BOOL isShowingAddToContactsLabel;
@property(retain) UILabel* addToContactsLabel;
@property(retain) UILabel* nameAndLabelLabel;
-(void)showAddToContactsLabel;
-(void)showName:(id)name label:(id)label animated:(BOOL)animated;
-(void)setHighlighted:(BOOL)highlighted;
-(CGSize)intrinsicContentSize;
-(void)dealloc;
-(id)textColorForHighlightedState:(BOOL)highlightedState;
-(id)initWithFrame:(CGRect)frame;
@end

