/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DialerLCDFieldProtocol.h"
#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UIGestureRecognizerDelegate.h"

@class PHHandsetDialerNameLabelView, NSLayoutConstraint, UILongPressGestureRecognizer, UIButton, UILabel;
@protocol DialerLCDFieldDelegate;

__attribute__((visibility("hidden")))
@interface PHHandsetDialerLCDView : XXUnknownSuperclass <DialerLCDFieldProtocol, UIGestureRecognizerDelegate> {
	BOOL _numberAccoutrementsVisible;
	BOOL _highlighted;
	BOOL _inCallMode;
	int _dialerType;
	UIButton* _deleteButton;
	id<DialerLCDFieldDelegate> _delegate;
	PHHandsetDialerNameLabelView* _nameAndLabelView;
	UILabel* _numberLabel;
	UILongPressGestureRecognizer* _longPressRecognizer;
	NSLayoutConstraint* _numberLabelVerticalConstraint;
	NSLayoutConstraint* _deleteButtonVerticalConstraint;
}
@property(retain) NSLayoutConstraint* deleteButtonVerticalConstraint;
@property(retain) NSLayoutConstraint* numberLabelVerticalConstraint;
@property(retain, nonatomic) UILongPressGestureRecognizer* longPressRecognizer;
@property(retain, nonatomic) UILabel* numberLabel;
@property(retain) PHHandsetDialerNameLabelView* nameAndLabelView;
@property(assign, nonatomic) BOOL inCallMode;
@property(assign, nonatomic) BOOL highlighted;
@property(assign, nonatomic) id<DialerLCDFieldDelegate> delegate;
@property(retain) UIButton* deleteButton;
@property(assign, nonatomic) int dialerType;
-(void)applyLayoutConstraints;
-(id)newDeleteButton;
-(id)newNameAndLabelView;
-(id)lcdColor;
-(void)handleLongPress:(id)press;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)paste:(id)paste;
-(void)copy:(id)copy;
-(BOOL)canPerformAction:(SEL)action withSender:(id)sender;
-(BOOL)resignFirstResponder;
-(BOOL)canBecomeFirstResponder;
-(void)_displayCallout;
-(void)_menuDidHide:(id)_menu;
-(void)_menuWillHide:(id)_menu;
-(void)_requestMakeCutCopyPasteCalloutVisible:(BOOL)visible;
-(void)_makeCalloutVisible:(BOOL)visible;
-(void)_setHighlighted:(BOOL)highlighted;
-(void)setNumberAccoutrementsVisible:(BOOL)visible animated:(BOOL)animated;
-(void)setName:(id)name numberLabel:(id)label;
-(void)deleteCharacter;
-(void)setText:(id)text needsFormat:(BOOL)format;
-(void)setText:(id)text needsFormat:(BOOL)format name:(id)name label:(id)label;
-(id)text;
-(void)dealloc;
-(CGSize)intrinsicContentSize;
-(BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;
-(id)initWithFrame:(CGRect)frame forDialerType:(int)dialerType;
-(id)numberLabelFont;
-(float)spacingBetweenLCDBottomAndNameView;
-(float)frameHeight;
-(float)numberLabelMinimumFontSize;
-(float)numberLabelMaximumFontSize;
-(float)deleteButtonVerticalConstantValue;
-(float)numberLabelVerticalConstantValue;
@end

