/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CALayer;

__attribute__((visibility("hidden")))
@interface PHInCallRingView : XXUnknownSuperclass {
	CALayer* _luminanceRingLayer;
	CALayer* _dodgeRingLayer;
	CALayer* _highlightDodgeLayer;
	CALayer* _highlightLuminanceLayer;
	CALayer* _selectionLayer;
}
@property(retain) CALayer* selectionLayer;
@property(retain) CALayer* highlightLuminanceLayer;
@property(retain) CALayer* highlightDodgeLayer;
@property(retain) CALayer* dodgeRingLayer;
@property(retain) CALayer* luminanceRingLayer;
+(id)_createRingImageWithSize:(CGSize)size strokeWidth:(float)width color:(id)color;
+(id)ringImageForDodge;
+(id)ringImageForLuminance;
-(CGSize)intrinsicContentSize;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(void)setEnabled:(BOOL)enabled;
-(void)setHighlighted:(BOOL)highlighted;
-(void)setSelected:(BOOL)selected;
@end

