/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView, UIImage, _UIBackdropView, UITransitionView;

__attribute__((visibility("hidden")))
@interface PhoneDesktopView : XXUnknownSuperclass {
	UIImageView* _imageView;
	UIImage* _wallpaperImage;
	UIImage* _queuedImage;
	BOOL _animatingTransition;
	_UIBackdropView* _backdropView;
	UITransitionView* _wallpaperContainer;
}
@property(retain) UITransitionView* wallpaperContainer;
@property(retain) _UIBackdropView* backdropView;
@property(readonly, assign, getter=isAnimatingTransition) BOOL animatingTransition;
-(void)transitionToQueuedImage;
-(void)reallyTransitionToImage:(id)image animated:(BOOL)animated;
-(void)transitionToImage:(id)image animated:(BOOL)animated;
-(id)initWithFrame:(CGRect)frame image:(id)image;
-(void)transitionViewDidComplete:(id)transitionView fromView:(id)view toView:(id)view3;
-(double)durationForTransition:(int)transition;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
@end

