/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import "PhoneTabViewController.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIViewController;

__attribute__((visibility("hidden")))
@interface PhoneNavigationController : XXUnknownSuperclass <PhoneTabViewController> {
	UIViewController<PhoneTabViewController>* _rootController;
}
+(BOOL)_isViewSizeFullScreen:(id)screen inWindow:(id)window;
+(id)defaultPNGName;
+(id)tabBarIconImageSelected;
+(id)tabBarIconImage;
+(id)tabBarIconName;
+(XXStruct_ndkk2A)badge;
+(int)tabViewType;
-(void)handleURL:(id)url;
-(void)prepareForSnapshot;
-(BOOL)shouldSnapshot;
-(void)presentViewController:(id)controller animated:(BOOL)animated completion:(id)completion;
-(void)pushViewController:(id)controller animated:(BOOL)animated;
-(void)setViewControllers:(id)controllers;
-(id)rootViewController;
-(void)_updateRootViewController;
-(void)dealloc;
-(id)initWithRootViewController:(id)rootViewController;
@end

