/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import "PhoneBadgeable.h"
#import "NSObject.h"


@protocol PhoneTabViewController <NSObject, PhoneBadgeable>
+(id)tabBarIconName;
+(id)defaultPNGName;
+(int)tabViewType;
-(void)handleURL:(id)url;
-(void)prepareForSnapshot;
-(BOOL)shouldSnapshot;
@optional
+(BOOL)requiresNavigationControllerContainer;
+(id)tabBarIconImageSelected;
+(id)tabBarIconImage;
+(id)tabBarIconImageName;
+(int)tabBarSystemItem;
-(BOOL)tabBarControllerShouldSelectViewController:(id)tabBarController;
-(void)tabBarDidSelectViewController;
@end

