/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PhoneBaseViewController.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class PHAddressBookController, PHVoicemailNavigationController, UINavigationController, PhoneNavigationController, DialerController, PHFavoritesViewController, PHRecentsViewController;

__attribute__((visibility("hidden")))
@interface PhoneTabBarController : XXUnknownSuperclass <PhoneBaseViewController> {
	PhoneNavigationController* _favoritesNavigationController;
	PhoneNavigationController* _recentsNavigationController;
	PHFavoritesViewController* _favoritesViewController;
	PHRecentsViewController* _recentsViewController;
	PHAddressBookController* _contactsViewController;
	DialerController* _keypadViewController;
	PHVoicemailNavigationController* _voicemailViewController;
}
@property(retain, nonatomic) PHVoicemailNavigationController* voicemailViewController;
@property(retain, nonatomic) DialerController* keypadViewController;
@property(retain, nonatomic) PHAddressBookController* contactsViewController;
@property(retain, nonatomic) PHRecentsViewController* recentsViewController;
@property(retain, nonatomic) PHFavoritesViewController* favoritesViewController;
@property(retain, nonatomic) UINavigationController* recentsNavigationController;
@property(retain, nonatomic) UINavigationController* favoritesNavigationController;
+(id)defaultPNGName;
+(int)statusBarStyle;
+(int)viewType;
-(void)transitionCompleted;
-(void)handleURL:(id)url;
-(void)prepareToHandleURL:(id)handleURL;
-(void)prepareForSnapshot;
-(BOOL)shouldSnapshot;
-(BOOL)shouldDisableEdgeClip;
-(id)viewControllerForTabViewType:(int)tabViewType;
-(int)tabTypeForViewController:(id)viewController;
-(void)transitionInFromViewType:(int)viewType animated:(BOOL)animated completionBlock:(id)block;
-(void)prepareForTransitionInFromViewType:(int)viewType animated:(BOOL)animated;
-(void)switchToTab:(int)tab;
-(int)currentTabViewType;
-(int)defaultTabViewType;
-(void)setSelectedViewController:(id)controller;
-(void)applicationDidResume;
-(void)_popCurrentNavigationControllerToRootViewControllerIfAppropriate;
-(void)showFavoritesTab:(BOOL)tab recentsTab:(BOOL)tab2 contactsTab:(BOOL)tab3 keypadTab:(BOOL)tab4 voicemailTab:(BOOL)tab5;
-(void)_badgeChanged:(id)changed;
-(void)_updateAllBadges:(BOOL)badges;
-(void)_stopListeningForBadgeChangedNotifications:(id)badgeChangedNotifications;
-(void)_startListeningForBadgeChangedNotifications:(id)badgeChangedNotifications;
-(BOOL)_reallyWantsFullScreenLayout;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)dealloc;
-(id)init;
@end

