/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSRecursiveLock, NSMutableArray;

__attribute__((visibility("hidden")))
@interface PHRecentsManager : XXUnknownSuperclass {
	BOOL _showsFaceTimeCalls;
	BOOL _showsFaceTimeAudioCalls;
	BOOL _showsTelephonyCalls;
	NSMutableArray* calls;
	NSRecursiveLock* callsLock;
}
@property(retain) NSRecursiveLock* callsLock;
@property(retain) NSMutableArray* calls;
@property(assign) BOOL showsTelephonyCalls;
@property(assign) BOOL showsFaceTimeAudioCalls;
@property(assign) BOOL showsFaceTimeCalls;
+(int)numberOfUnseenMissedCalls;
-(BOOL)dialRecentCall:(id)call;
-(void)deleteCall:(id)call;
-(void)deleteAllCalls;
-(id)recentCalls;
-(void)reloadCallsArray;
-(void)reloadCallsArrayIfNecessary;
-(id)copyDisplayableCTCalls;
-(BOOL)recentsArray:(id)array representsCTCallsArray:(id)array2;
-(id)copyRecentCallsArrayWithCTCalls:(id)ctcalls;
-(void)markRepresentedCallsAsSeen;
-(void)applicationDidReceiveMemoryWarningNotification:(id)application;
-(void)phoneApplicationLocaleChangedNotification:(id)notification;
-(void)phoneApplicationAddressBookChangedNotification:(id)notification;
-(void)homeCountryCodeChangedNotification:(id)notification;
-(void)faceTimeAvailabilityChangedNotification:(id)notification;
-(void)callHistorySignificantChangeNotification;
-(void)callHistoryRecordAddedNotification:(CTCallRef)notification;
-(void)dealloc;
-(id)init;
@end

