/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import "PHRecentsPersonHeaderView.h"


__attribute__((visibility("hidden")))
@interface PHRecentsPersonPhoneHeaderView : PHRecentsPersonHeaderView {
}
-(id)newSummaryViewForRecentCall:(id)recentCall occurrenceDate:(id)date type:(int)type duration:(double)duration category:(int)category dataUsage:(double)usage;
@end

