/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface PHRecentsToggleButton : XXUnknownSuperclass {
}
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(id)initWithWidth:(float)width leftTitle:(id)title rightTitle:(id)title3;
@end

