/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import "PHRecentsPersonHeaderSummaryView.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

__attribute__((visibility("hidden")))
@interface PHRecentsPersonFaceTimeHeaderSummaryView : XXUnknownSuperclass <PHRecentsPersonHeaderSummaryView> {
	UILabel* _topmostLabel;
	UILabel* _bottommostLabel;
	float _intrinsicContentHeight;
}
@property(assign) float intrinsicContentHeight;
@property(assign) UILabel* bottommostLabel;
@property(assign) UILabel* topmostLabel;
-(CGSize)sizeThatFits:(CGSize)fits;
-(CGSize)intrinsicContentSize;
-(id)initWithFrame:(CGRect)frame recentCall:(id)call occurrenceDate:(id)date type:(int)type duration:(double)duration category:(int)category dataUsage:(double)usage;
@end

