/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class PHRecentCall, UILabel, UIImageView, NSLayoutConstraint, NSDictionary, UIDateLabel, NSArray;

__attribute__((visibility("hidden")))
@interface PHRecentsCell : XXUnknownSuperclass {
	UILabel* _callerNameLabel;
	UILabel* _callerLabelLabel;
	UILabel* _callerCountLabel;
	UIDateLabel* _callerDateLabel;
	UIImageView* _callTypeIconView;
	NSDictionary* _allViewsDictionary;
	long _buildConstraintsOnceToken;
	NSLayoutConstraint* _topConstraint;
	NSLayoutConstraint* _bottomConstraint;
	PHRecentCall* _call;
	NSArray* _calculatedConstraints;
}
@property(retain, nonatomic) NSArray* calculatedConstraints;
@property(readonly, assign) NSDictionary* allMetrics;
@property(readonly, assign) NSDictionary* allViews;
@property(readonly, assign) int count;
@property(retain, nonatomic) PHRecentCall* call;
+(id)allMetrics;
+(float)height;
+(float)editingMarginWidth;
+(float)marginWidth;
+(id)_sharedOutgoingSelectedFaceTimeImage;
+(id)_sharedOutgoingFaceTimeImage;
+(id)_sharedOutgoingSelectedCallImage;
+(id)_sharedOutgoingCallImage;
-(void)_updateFonts;
-(void)_handleContentSizeDidChange:(id)_handleContentSize;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)updateConstraints;
-(void)_recalculateConstraints;
-(void)_buildConstraints;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

