/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIGestureRecognizerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "TPStarkInCallViewControllerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, TPStarkInCallViewController, UIViewController;

__attribute__((visibility("hidden")))
@interface PHStarkInCallViewController : XXUnknownSuperclass <UIGestureRecognizerDelegate, TPStarkInCallViewControllerDelegate, UINavigationControllerDelegate> {
	BOOL _nextBackDismissesNavController;
	UIViewController* _contactsViewController;
	UIView* _flippyViewContainer;
	TPStarkInCallViewController* _mainInCallViewController;
}
@property(retain) TPStarkInCallViewController* mainInCallViewController;
@property(retain) UIView* flippyViewContainer;
+(id)latestInCallViewController;
-(BOOL)gestureRecognizer:(id)recognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)gestureRecognizer;
-(void)hardwareControlEventNotification:(id)notification;
-(void)dismissalRequestedFromInCallViewController:(id)callViewController;
-(void)presentKeypadViewControllerRequestedFromInCallViewController:(id)callViewController;
-(void)cancelAddCallViewController:(id)controller;
-(void)backPressed:(id)pressed;
-(void)dismissViewControllerAnimated:(BOOL)animated completion:(id)completion;
-(void)navigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)presentAddCallViewControllerRequestedFromInCallViewController:(id)callViewController;
-(BOOL)activePhoneCallExists;
-(void)animateOutIfNecessary;
-(void)updateTPInCallControllerPhoneCalls;
-(void)queueUpdateToTPIncallControllerPhoneCalls;
-(void)conferencedCallsChangedNotification:(id)notification;
-(void)displayedCallsChangedNotification:(id)notification;
-(void)incomingCallChangedNotification:(id)notification;
-(void)muteStateChangedNotification:(id)notification;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)loadView;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

