/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PHStarkGenericTableViewController.h"


__attribute__((visibility("hidden")))
@interface PHStarkFavoritesViewController : PHStarkGenericTableViewController {
}
-(float)defaultRowHeight;
-(id)subtitleForNoContentBanner;
-(id)titleForNoContentBanner;
-(void)programmaticallySelectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)favoritesManagerSignificantChangeNotification:(id)notification;
-(void)dealloc;
-(id)init;
@end

