/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class PHStarkRootContainerViewController, UINavigationController, PHStarkHardwareControlsBroadcaster, UIWindow;

__attribute__((visibility("hidden")))
@interface PHStarkManager : XXUnknownSuperclass {
	PHStarkRootContainerViewController* _containerViewController;
	UIWindow* _starkWindow;
	PHStarkHardwareControlsBroadcaster* _hardwareControlsBroadcaster;
	PHStarkRootContainerViewController* _rootContainerViewController;
}
@property(retain) PHStarkRootContainerViewController* rootContainerViewController;
@property(retain) PHStarkHardwareControlsBroadcaster* hardwareControlsBroadcaster;
@property(readonly, assign) BOOL activeInterfaceMechanismIsHardware;
@property(readonly, assign) UINavigationController* starkNavigationController;
@property(retain) UIWindow* starkWindow;
@property(retain) PHStarkRootContainerViewController* containerViewController;
+(id)starkScreen;
+(id)sharedStarkManager;
-(void)screenshotStarkScreen;
-(void)attachStarkToScreen:(id)screen;
-(void)screenDidDisconnectNotification:(id)screen;
-(void)screenDidConnectNotification:(id)screen;
-(void)dealloc;
-(id)init;
@end

