/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UINavigationControllerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UINavigationController, PHStarkMainMenuContainerViewController;

__attribute__((visibility("hidden")))
@interface PHStarkRootContainerViewController : XXUnknownSuperclass <UINavigationControllerDelegate> {
	UINavigationController* _wrapperNavigationController;
	PHStarkMainMenuContainerViewController* _mainMenuContainerViewController;
}
@property(retain) PHStarkMainMenuContainerViewController* mainMenuContainerViewController;
@property(retain) UINavigationController* wrapperNavigationController;
-(void)navigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)viewWillAppear:(BOOL)view;
-(void)loadView;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

