/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@protocol PHStarkTelephonyStateMonitorDelegate;

__attribute__((visibility("hidden")))
@interface PHStarkTelephonyStateMonitor : XXUnknownSuperclass {
	id<PHStarkTelephonyStateMonitorDelegate> _delegate;
	int _state;
}
@property(assign, nonatomic) int state;
@property(assign) id<PHStarkTelephonyStateMonitorDelegate> delegate;
-(void)_phoneApplicationDisplayedCallsChangedNotification:(id)notification;
-(void)stopMonitoringTelephonyState;
-(void)startMonitoringTelephonyState;
-(int)currentState;
-(void)dealloc;
-(id)init;
@end

