/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class DialerController, UIButton;

__attribute__((visibility("hidden")))
@interface PHStarkInCallKeypadViewController : XXUnknownSuperclass {
	UIButton* _backButton;
	UIButton* _endButton;
	DialerController* _dialerController;
	int _currentHighlightedControlIndex;
}
@property(assign) int currentHighlightedControlIndex;
@property(retain) DialerController* dialerController;
@property(retain) UIButton* endButton;
@property(retain) UIButton* backButton;
-(void)_physicalButtonsCancelled:(id)cancelled withEvent:(id)event;
-(void)_physicalButtonsEnded:(id)ended withEvent:(id)event;
-(void)_physicalButtonsBegan:(id)began withEvent:(id)event;
-(void)_wheelChangedWithEvent:(id)event;
-(void)endButtonTapped:(id)tapped;
-(void)backButtonTapped:(id)tapped;
-(void)loadView;
-(void)dealloc;
@end

