/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView;

__attribute__((visibility("hidden")))
@interface PHStarkGenericTableViewCell : XXUnknownSuperclass {
	BOOL _showsChevron;
	BOOL _hidesChevronWhenUnhighlighted;
	UIImageView* _chevronImageView;
}
@property(retain) UIImageView* chevronImageView;
@property(assign, nonatomic) BOOL hidesChevronWhenUnhighlighted;
@property(assign, nonatomic) BOOL showsChevron;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

