/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import "DialerLCDFieldProtocol.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

__attribute__((visibility("hidden")))
@interface PHStarkInCallDialerLCDView : XXUnknownSuperclass <DialerLCDFieldProtocol> {
	UILabel* _mainNumberLabel;
}
@property(retain) UILabel* mainNumberLabel;
-(void)setLabel:(id)label;
-(id)name;
-(void)setName:(id)name;
-(void)setHighlighted:(BOOL)highlighted;
-(BOOL)highlighted;
-(void)setInCallMode:(BOOL)callMode;
-(BOOL)inCallMode;
-(CGSize)intrinsicContentSize;
-(void)setDelegate:(id)delegate;
-(void)deleteCharacter;
-(void)setText:(id)text needsFormat:(BOOL)format;
-(id)text;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

