/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDelegate.h"
#import "MobilePhone-Structs.h"
#import "UITableViewDataSource.h"
#import "PHStarkGenericViewController.h"

@class PHStarkNoContentBannerView, NSString, UITableView;

__attribute__((visibility("hidden")))
@interface PHStarkGenericTableViewController : PHStarkGenericViewController <UITableViewDataSource, UITableViewDelegate> {
	BOOL _tableViewReloadIsRequiredOnViewWillAppear;
	BOOL _viewIsInAppearedState;
	UITableView* _mainTableView;
	PHStarkNoContentBannerView* _noContentBannerView;
}
@property(retain) PHStarkNoContentBannerView* noContentBannerView;
@property(readonly, assign) NSString* badgeString;
@property(readonly, assign) BOOL viewIsInAppearedState;
@property(assign) BOOL tableViewReloadIsRequiredOnViewWillAppear;
@property(retain) UITableView* mainTableView;
-(void)updateBadgeString;
-(id)subtitleForNoContentBanner;
-(id)titleForNoContentBanner;
-(void)setNoContentBannerShown:(BOOL)shown;
-(void)hardwareControlEventNotification:(id)notification;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)programmaticallySelectRowAtIndexPath:(id)indexPath;
-(BOOL)shouldRespondToHardwareControlEvent;
-(void)dealloc;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(float)defaultRowHeight;
-(void)loadView;
-(void)applicationBadgeChangedNotification:(id)notification;
-(id)init;
@end

