/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PHStarkGenericTableViewCell.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface PHStarkActionSheetTableViewCell : PHStarkGenericTableViewCell {
	UILabel* _mainLabel;
	UILabel* _secondaryLabel;
}
@property(retain) UILabel* secondaryLabel;
@property(retain) UILabel* mainLabel;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

