/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PHStarkGenericTableViewCell.h"

@class UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface PHStarkHardwareMenuTableViewCell : PHStarkGenericTableViewCell {
	UILabel* _mainLabel;
	UIImageView* _iconImageView;
}
@property(retain) UIImageView* iconImageView;
@property(retain) UILabel* mainLabel;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

