/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, NSString;

__attribute__((visibility("hidden")))
@interface PHStarkNoContentBannerView : XXUnknownSuperclass {
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;
}
@property(retain) UILabel* subtitleLabel;
@property(retain) UILabel* titleLabel;
@property(retain, nonatomic) NSString* subtitleString;
@property(retain, nonatomic) NSString* titleString;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

