/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

__attribute__((visibility("hidden")))
@interface PHStarkLozengeLabel : XXUnknownSuperclass {
	BOOL _highlighted;
	UILabel* _label;
}
@property(assign, nonatomic) BOOL highlighted;
@property(retain) UILabel* label;
-(void)dealloc;
-(CGSize)intrinsicContentSize;
-(BOOL)isHighlighted;
-(id)init;
@end

