/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import "PHStarkGenericTableViewController.h"


__attribute__((visibility("hidden")))
@interface PHStarkVoicemailViewController : PHStarkGenericTableViewController {
}
-(id)badgeString;
-(id)subtitleForNoContentBanner;
-(id)titleForNoContentBanner;
-(void)programmaticallySelectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)voicemailViewControllerPlayVoicemailEventNotification:(id)notification;
-(void)voicemailManagerChangedNotification:(id)notification;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

