/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UITableView, UILabel;

__attribute__((visibility("hidden")))
@interface PHStarkActionSheetViewController : XXUnknownSuperclass {
	UILabel* _headerLabel;
	UITableView* _tableView;
}
@property(retain) UITableView* tableView;
@property(retain) UILabel* headerLabel;
-(void)_physicalButtonsBegan:(id)began withEvent:(id)event;
-(void)dealloc;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)loadView;
@end

