/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface PHStaticDialerPad : XXUnknownSuperclass {
	int _dialerType;
}
@property(assign) int dialerType;
-(CGSize)intrinsicContentSize;
-(float)_yFudge;
-(id)_highlightedImage;
-(id)_keypadImage;
-(id)_pressedImage;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithDialerType:(int)dialerType;
@end

