/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSTimer, NSArray;

__attribute__((visibility("hidden")))
@interface PHTextCycleLabel : XXUnknownSuperclass {
	NSArray* _cycleStrings;
	NSTimer* _cycleTimer;
	int _currentCycleStringIndex;
}
@property(assign) int currentCycleStringIndex;
@property(retain) NSTimer* cycleTimer;
@property(retain) NSArray* cycleStrings;
-(void)dealloc;
-(void)setText:(id)text;
-(void)cycleToNextString;
-(void)startCyclingStrings;
@end

