/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PHAudioPlayerDelegate.h"
#import "MPDetailSliderDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class NSString, NSArray, PHVoicemailSlider, NSDate, NSMutableArray, UIDateLabel, UIGestureRecognizer, UIButton, VMVoicemail, UILabel, UIActionSheet, UIImageView, NSLayoutConstraint;
@protocol PHVoicemailCellDelegate, PHVoicemailCellConfigurationDelegate;

__attribute__((visibility("hidden")))
@interface PHVoicemailCell : XXUnknownSuperclass <PHAudioPlayerDelegate, MPDetailSliderDelegate, UIActionSheetDelegate, UIGestureRecognizerDelegate> {
	UIImageView* _unreadIndicatorView;
	UILabel* _nameLabel;
	UILabel* _labelLabel;
	UILabel* _durationLabel;
	UIButton* _infoButton;
	UIDateLabel* _dateLabel;
	UILabel* _longDateLabel;
	UIButton* _playPauseButton;
	PHVoicemailSlider* _sliderView;
	UIButton* _speakerButton;
	UIButton* _callBackButton;
	UIButton* _deleteButton;
	long _createConstraintsOnceToken;
	NSMutableArray* _calculatedConstraints;
	NSLayoutConstraint* _nameLabelYConstraint;
	NSLayoutConstraint* _labelLabelYConstraint;
	NSLayoutConstraint* _infoButtonXConstraint;
	NSLayoutConstraint* _infoButtonYConstraint;
	NSLayoutConstraint* _unreadIndicatorYConstraint;
	NSLayoutConstraint* _playPauseAndControlsYConstraint;
	NSLayoutConstraint* _buttonsYConstraint;
	BOOL _animatingUpdateToUnreadIndicator;
	BOOL _shouldReupdateUnreadIndicator;
	BOOL _playWhenAvailable;
	BOOL _trackingTouchInCloseVoicemailArea;
	UIGestureRecognizer* _closeVoicemailGestureRecognizer;
	BOOL _showingPlayController;
	VMVoicemail* _voicemail;
	id<PHVoicemailCellConfigurationDelegate> _configurationDelegate;
	id<PHVoicemailCellDelegate> _delegate;
	UIActionSheet* _audioSelectionActionSheet;
	NSArray* _audioSelectionActionSheetRoutes;
}
@property(assign) NSArray* audioSelectionActionSheetRoutes;
@property(assign) UIActionSheet* audioSelectionActionSheet;
@property(readonly, assign) int audioButtonMode;
@property(readonly, assign) BOOL unread;
@property(assign, nonatomic) BOOL showingPlayController;
@property(assign, nonatomic) id<PHVoicemailCellDelegate> delegate;
@property(assign, nonatomic) id<PHVoicemailCellConfigurationDelegate> configurationDelegate;
@property(retain, nonatomic) VMVoicemail* voicemail;
@property(readonly, assign, nonatomic) BOOL unread;
@property(readonly, assign, nonatomic) unsigned playingStatus;
@property(readonly, assign, nonatomic) NSString* dateLabelAccessabilityString;
@property(readonly, assign, nonatomic) NSDate* date;
@property(readonly, assign, nonatomic) NSString* labelString;
@property(readonly, assign, nonatomic) NSString* nameString;
+(BOOL)isRTLLanguage;
+(float)heightShowingPlayControllerWithVoicemail:(id)voicemail;
+(float)contentViewHeightCollapsed;
+(float)height;
+(id)pauseImage;
+(id)disabledPlayImage;
+(id)playImage;
-(id)tableViewSeparatorColor;
-(void)trashButtonTapped:(id)tapped withEvent:(id)event;
-(void)callButtonTapped:(id)tapped withEvent:(id)event;
-(void)speakerButtonTapped:(id)tapped withEvent:(id)event;
-(void)playPauseButtonTapped:(id)tapped withEvent:(id)event;
-(void)customAccessoryButtonTapped:(id)tapped withEvent:(id)event;
-(void)_closeVoicemailFromGestureRecognizerTap:(id)gestureRecognizerTap;
-(BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;
-(BOOL)_pointIsInsideCloseVoicemailRect:(CGPoint)rect;
-(id)_automationID;
-(void)_updatePlayPauseButton;
-(void)_updateUnreadIndicatorAnimated:(BOOL)animated;
-(void)_updateUI;
-(void)_updateDurationLabel;
-(void)_updateProx;
-(void)_updateSpeakerButton;
-(void)_updatePlaybackTimer;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)layoutSubviews;
-(void)updateConstraints;
-(void)detailSlider:(id)slider didChangeValue:(float)value;
-(void)detailSliderTrackingDidCancel:(id)detailSliderTracking;
-(void)detailSliderTrackingDidEnd:(id)detailSliderTracking;
-(void)detailSliderTrackingDidBegin:(id)detailSliderTracking;
-(void)stoppedPlayingWithDataSource:(id)dataSource withError:(id)error;
-(void)updateWithElapsedTime:(double)elapsedTime playableTime:(double)time totalTime:(double)time3 isPlaying:(BOOL)playing isPlayable:(BOOL)playable dataSource:(id)source;
-(void)startedPlayingWithDataSource:(id)dataSource;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)_handleContentSizeDidChange:(id)_handleContentSize;
-(void)_deregisterForVoicemailNotifications;
-(void)_registerForVoicemailNotifications;
-(void)_handleAudioControllerChanged:(id)changed;
-(void)_handleVoicemailDataAvailableChanged:(id)changed;
-(void)_handleVoicemailFlagsChanged:(id)changed;
-(void)_handlePhoneAppAddressBookChanged:(id)changed;
-(void)startPlaying;
-(CGPoint)anchorPointForUpdateInWindow:(id)window;
-(void)setShowingPlayController:(BOOL)controller animated:(BOOL)animated;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(void)_updateFonts;
@end

