/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <MediaPlayer/MPDetailSlider.h>
#import "MobilePhone-Structs.h"


__attribute__((visibility("hidden")))
@interface PHVoicemailSlider : MPDetailSlider {
}
-(void)reset;
-(float)timeLabelVerticalOffsetForStyle:(int)style;
-(id)_modernThumbImageWithColor:(id)color height:(float)height;
-(id)timeLabelTextColorForStyle:(int)style;
-(id)timeLabelFontForStyle:(int)style;
-(id)initWithFrame:(CGRect)frame;
@end

