/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

__attribute__((visibility("hidden")))
@interface PHVoicemailGreetingCell : XXUnknownSuperclass {
	UILabel* _greetingTextLabel;
}
@property(assign) UILabel* greetingTextLabel;
-(void)_updateFonts;
-(void)_handleContentSizeDidChange:(id)_handleContentSize;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

