/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RadiosPreferencesDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIButton, RadiosPreferences, UIView, UILabel, UIColor, NSArray;

__attribute__((visibility("hidden")))
@interface PHVoicemailUnavailableCell : XXUnknownSuperclass <RadiosPreferencesDelegate> {
	BOOL _showCallVoicemailButton;
	UIColor* _tableViewSeparatorColor;
	UILabel* _voicemailUnavailableLabel;
	UIButton* _callVoicemailButton;
	UIView* _bottomLineView;
	UIView* _topLineView;
	NSArray* _mutableConstraints;
	RadiosPreferences* _radiosPreferences;
}
@property(retain) RadiosPreferences* radiosPreferences;
@property(assign, nonatomic) BOOL showCallVoicemailButton;
@property(retain) NSArray* mutableConstraints;
@property(assign) UIView* topLineView;
@property(assign) UIView* bottomLineView;
@property(assign) UIButton* callVoicemailButton;
@property(assign) UILabel* voicemailUnavailableLabel;
@property(retain, nonatomic) UIColor* tableViewSeparatorColor;
+(float)height;
-(void)callVoicemail;
-(void)_handleContentSizeDidChange:(id)_handleContentSize;
-(void)airplaneModeChanged;
-(void)_updateFonts;
-(void)_updateCallVoicemailButton;
-(void)updateConstraints;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

