/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PHVoicemailListViewController.h"
#import "PHVoicemailListViewControllerConcrete.h"
#import "UIActionSheetDelegate.h"

@class UIActionSheet, NSString, NSArray;

__attribute__((visibility("hidden")))
@interface PHVoicemailTrashListViewController : PHVoicemailListViewController <UIActionSheetDelegate, PHVoicemailListViewControllerConcrete> {
	UIActionSheet* _clearAllConfirmationActionSheet;
}
@property(readonly, assign) NSArray* childListControllers;
@property(readonly, assign) NSString* navigationBarTextWithCountFormat;
@property(readonly, assign) NSString* tableViewDestructiveActionText;
@property(readonly, assign) BOOL popOffIfEmpty;
@property(readonly, assign) unsigned flagsNotToHave;
@property(readonly, assign) unsigned flagsToHave;
@property(readonly, assign) NSString* folderName;
@property(readonly, assign) NSString* navigationBarText;
@property(readonly, assign) NSString* cellDetailDestructiveActionText;
-(void)_updateClearAllEnabled;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)_trashHandleVoicemailTaskStartedOrEnded:(id)ended;
-(void)clearAllTapped;
-(void)viewWillAppear:(BOOL)view;
-(void)willShowVoicemails:(id)voicemails;
-(void)performCellDetailDestructiveActionForVoicemail:(id)voicemail;
-(void)performTableViewDestructiveActionForVoicemail:(id)voicemail;
-(void)dealloc;
-(id)initWithNavigationController:(id)navigationController;
@end

