/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TPSetPINViewControllerDelegate.h"
#import "PHVoicemailGreetingViewControllerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSTimer, PHVoicemailNavigationController, PhoneNavigationController;
@protocol PHVoicemailSetupViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface PHVoicemailSetupViewController : XXUnknownSuperclass <TPSetPINViewControllerDelegate, PHVoicemailGreetingViewControllerDelegate> {
	PHVoicemailNavigationController* _navigationController;
	NSTimer* _passwordChangeTimedOutTimer;
	id<PHVoicemailSetupViewControllerDelegate> _voicemailSetupDelegate;
	PhoneNavigationController* _setupPINAndGreetingNavigationController;
}
@property(retain) PhoneNavigationController* setupPINAndGreetingNavigationController;
@property(assign) id<PHVoicemailSetupViewControllerDelegate> voicemailSetupDelegate;
@property(assign) PHVoicemailNavigationController* navigationController;
-(BOOL)_hasValidProvisionalPIN;
-(void)_setupNoContentViewForInitialSetup;
-(void)_handleVoicemailPasswordChangeTimedOut;
-(void)_handleVoicemailPasswordChangeTaskNotification:(id)notification;
-(void)voicemailGreetingViewControllerFinished:(id)finished;
-(void)setPINViewControllerFinished:(id)finished success:(BOOL)success oldPIN:(id)pin newPIN:(id)pin4;
-(void)_voicemailSetupButtonTapped;
-(void)reset;
-(void)loadView;
-(void)dealloc;
-(id)initWithNavigationController:(id)navigationController;
@end

