/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PHVoicemailCellConfigurationDelegate.h"

@class NSString, NSArray;

@protocol PHVoicemailListViewControllerConcrete <PHVoicemailCellConfigurationDelegate>
@optional
@property(readonly, assign) NSArray* childListControllers;
@property(readonly, assign) NSString* navigationBarTextWithCountFormat;
@required
@property(readonly, assign) NSString* tableViewDestructiveActionText;
@property(readonly, assign) BOOL popOffIfEmpty;
@property(readonly, assign) unsigned flagsNotToHave;
@property(readonly, assign) unsigned flagsToHave;
@property(readonly, assign) NSString* folderName;
@property(readonly, assign) NSString* navigationBarText;
-(void)performTableViewDestructiveActionForVoicemail:(id)voicemail;
@optional
-(void)willShowVoicemails:(id)voicemails;
@end

