/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSString, NSArray, NSNumber, NSObject, AVController;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface PHVoicemailAudioController : XXUnknownSuperclass {
	NSString* _category;
	AVController* _avController;
	NSObject<OS_dispatch_queue>* _avControllerQueue;
	NSObject<OS_dispatch_queue>* _pickableRoutesQueue;
	NSObject<OS_dispatch_queue>* _pickedRouteQueue;
	NSArray* _pickableRoutes;
	NSDictionary* _pickedRoute;
	NSDictionary* _forcedPickedRoute;
	BOOL _isRequestingPickableRoutes;
	BOOL _isRequestingPickedRoute;
	unsigned long long _lastPickableRoutesScheduleTime;
	unsigned long long _lastPickedRouteScheduleTime;
	NSNumber* _currentTimeOverride;
}
@property(retain) NSNumber* currentTimeOverride;
@property(assign) double currentTime;
@property(readonly, assign) AVController* avController;
@property(readonly, assign) NSDictionary* speakerRoute;
@property(readonly, assign) NSDictionary* receiverRoute;
@property(readonly, assign) int pickedRouteType;
@property(copy, nonatomic) NSDictionary* pickedRoute;
@property(readonly, assign) NSArray* pickableRoutes;
-(void)_mediaServerDied:(id)died;
-(void)_pickableRoutesChanged:(id)changed;
-(id)_pickableRoutesForceNewRequest:(BOOL)request;
-(id)_pickedRouteForceNewRequest:(BOOL)request;
-(void)_avControllerTimeJumpedAfterReset:(id)reset;
-(int)typeForRoute:(id)route;
-(void)dealloc;
-(id)initForVoicemailGreeting;
-(id)initForVoicemail;
-(id)_initWithCategory:(id)category;
@end

