/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class PHInCallRingView;

__attribute__((visibility("hidden")))
@interface SixSquareButton : XXUnknownSuperclass {
	UIEdgeInsets _contentInsets;
	PHInCallRingView* _ringView;
}
@property(retain) PHInCallRingView* ringView;
-(void)setEnabled:(BOOL)enabled;
-(void)setSelected:(BOOL)selected;
-(void)setHighlighted:(BOOL)highlighted;
-(void)setContentRect:(CGRect)rect;
-(CGRect)imageRectForContentRect:(CGRect)contentRect;
-(CGRect)titleRectForContentRect:(CGRect)contentRect;
-(void)setupButton;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

