/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SixSquareButton;

__attribute__((visibility("hidden")))
@interface SixSquareView : XXUnknownSuperclass {
	SixSquareButton* _buttons[6];
	id _delegate;
	BOOL _onlyShowsFourButtons;
}
@property(assign, nonatomic) BOOL onlyShowsFourButtons;
-(void)setAllButtonsEnabled:(BOOL)enabled;
-(id)buttonAtPosition:(int)position;
-(void)_cancelButtonDown:(id)down;
-(void)_buttonDown:(id)down;
-(void)_buttonHeldDownShort:(id)aShort;
-(void)_buttonHeldDown:(id)down;
-(void)_buttonClicked:(id)clicked;
-(void)setTitle:(id)title image:(id)image selectedImage:(id)image3 forPosition:(int)position;
-(void)setDelegate:(id)delegate;
-(void)removeFromSuperview;
-(CGSize)totalSize;
-(CGSize)intrinsicContentSize;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

