/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol TPSetPINViewControllerDelegate
-(void)setPINViewControllerFinished:(id)finished success:(BOOL)success oldPIN:(id)pin newPIN:(id)pin4;
@end

