/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface XXUnknownSuperclass (VoicemailExtras)
-(void)displayedErrorTitle:(id*)title message:(id*)message;
@end

@interface XXUnknownSuperclass (DayComparison)
-(BOOL)isSameDayAsDate:(id)date;
@end

@interface XXUnknownSuperclass (VoicemailCellAdditions)
@property(readonly, assign, nonatomic) BOOL isDeletedRow;
@end

@interface XXUnknownSuperclass (VoicemailAudioRouting)
-(id)dictionaryForAudioRoutingComparison;
@end

@interface XXUnknownSuperclass (MobilePhone)
@property(readonly, assign) BOOL hasCallbackNumber;
@property(readonly, assign) BOOL hasValidLabel;
-(void)setRead;
-(void)moveFromTrash;
-(void)moveToTrash;
-(void)deleteForever;
-(void)callBack;
@end

@interface XXUnknownSuperclass (UIFont_InCallLCDView)
+(id)_thinSystemFontWithDialerCharacteristicsOfSize:(float)size;
@end

@interface XXUnknownSuperclass (PHVoicemailAudioController)
@property(readonly, assign) NSString* routeName;
@end

@interface XXUnknownSuperclass (MobilePhoneAdditions)
+(id)phPathForImageNamed:(id)imageNamed inBundle:(id)bundle;
+(id)phPathForImageNamed:(id)imageNamed;
+(id)phImageNamed:(id)named;
+(id)phImageNamed:(id)named inBundle:(id)bundle;
@end

@interface XXUnknownSuperclass (MobilePhoneAdditions)
+(id)phPreferredItalicFontForTextStyle:(id)textStyle;
+(id)phPreferredBoldFontForTextStyle:(id)textStyle;
+(id)phPreferredFontForTextStyle:(id)textStyle;
@end

@interface XXUnknownSuperclass (Testing)
+(int)tabViewType;
-(void)transitionCompleted;
-(void)_finishSwitchTest;
-(BOOL)runTest:(id)test options:(id)options;
-(void)willStartTest:(id)test;
@end

@interface XXUnknownSuperclass (MPRecentsExtensions)
-(id)asIndexPaths;
@end

@interface XXUnknownSuperclass (MPRecentsExtensions)
-(id)indexPathsForCallsOfStatus:(int)status;
@end

@interface XXUnknownSuperclass (PHStarkExtensions)
-(void)deselectRowAtIndexPathIfNotUsingHardwareControls:(id)indexPathIfNotUsingHardwareControls animated:(BOOL)animated;
@end

